version: '3.8'
services:
  server:
    build: ./server
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: test
      DB_PASSWORD: test123
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8081:8081"
  client:
    build: ./client
    ports: 
      - "8080:8080"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
