version: '3.8'
services:
  server:
    build: ./server
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: test
      DB_PASSWORD: test123
      DB_PORT: 5432
      DATABASE_URL: postgres://test:test123@db:5432/mydb
    depends_on:
      - db
    ports:
      - "8081:8081"
  client:
    build: ./client
    ports: 
      - "8080:8080"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
      POSTGRES_PORT: 5432
    volumes: 
      # - ./postgres-data:/var/lib/postgresql/data
      - ./server/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
